os: linux
dist: bionic
language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  on:
    tags: true
    repo: anastasiia-kornilova/map_metrics
    python: 3.8
  password:
    secure: MV0CvvqmX9yX3qh3bKaRCsAd5VVs9POHJNf+ITCgG8sM/AwD1XO4r0hP7mPt8/a0HcLkUCb/ruxF3yim8PGGEJJe2WDF/CxiqysvFfz33LvRFu5WOdlpoiT7YhgF/UP7g+gmMvp6rtnIbGrAk7X+gNaCKKAIjIJiudc0Gu6ED5PMHOGl1o3NkAyhB+E8OG0lHHzo9qFJ+FfZQKjY8dXBHgGfCArCUx2PcGA1rYhISIRFvqKJ64BK3HUo0WKPQzn9SVKoPqmdqGxCKjS9apP0sSfj7g15cGa5tetnb2mZWG708oy6sgOBrs9IEG9wWRArnIaojLecFOI0D66JILr/2zE114PsgRIusTFveHy3G5Oi0pum3+Yz+bKfv3PxRA1e8QUQEcNsoZ1tW0VLfsPJCGWzT4lBYK9J4INGj2OzpbbGCsR2jYPXG5IV5E+vICc9czRAcQXjIU94RyJBVZsG+Y7pmoviVWhiQMZQ7tn9QbPo7ctT5QIwsrxCjOGzRuZmze3lt08RsyzuvSiZ/tCCayGki+5uGR5K9edBX19pmk+EjEpzT6d3ez6pIHGxbfsFUOwywAHj9/7yQNuOURKKcjC9n35hUO5jLYcGHLUJOCBGCJ7+vIbtJIBG2RJXm1l/6QIkTKEsvVZkfp9K0GJzEYR3a5tqqN8AqHCVXCmGNSM=
env:
  global:
    secure: XNCSkYwPl0bJhafKN8/hZfrQoK80mdj9XiLwI3VisbIQJq9t04iZLtNERk1d1K6wHO+qTeGEkcRxsIQ14zyT0hyBn031BWE6C87YZ7KVBEKE2YrIKK4ix9ddtCpBOQfwwn46Vd/qR3X3guSOr2F0SpyP3hzGl8d0CPzO7ekOP8ljprzQDVOxEqE38jbYxf9WuBfIHqZBNIyjua7gqIQc1lj0oOTdAGgxPVOkNPhETUTovsdcbKydKwgja5fsgFLCLlsseMP/Cgwe/HYTPL8QTXsqoZadiy4omdGMGclH0udqKXiM7JnWhSkOGkoPZuk/Z41lTr/eKnb/oHAeIlr7q3ZqGfO8u2MHyePe5A+2KjpMUZY0NAbQ/wJaxNHDTRaWx1+Fw5GuHrK8rr5StcEyu5sAXhf3IGHhACQCcBmhpnP2SP+moW8KbcmFUu4GIM+AfVta04pub/4VJqX+wN6dYS2ptJq8o+YMj4zqJVpT48+swg2kdsRCN1GvOoxul7sKX07CsPrDTo/jRT0GClo1zqRlveDPgfy38Siby3a/rymUHdfVJXrsRXin5A2xBhBW9myW22E3DaS1AGTU4FCPZFdVHmZmk63wG05gtIM1syxs/JSRM5QTAWlG0MUCKNQbm1xXb2da6feDRCiZ/1Ql0geY2N4vQSM6rL655kYerIw=
