# # # # # # # # #
# Source: https://github.com/miloserdova-l/mrob/blob/feature/windows-wheel/.github/workflows/wheels.yml
# # # # # # # # #
name: Build wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build map_metrics project
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./lib
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install required packages from distro
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git build-essential g++ cmake python3-distutils python3-dev python3-numpy python3-pip libboost-graph-dev
          python3 -m pip install pytest

      - name: Configure and build native map_metrics library with Python bindings
        run: |
          mkdir -p build
          cmake -S $PWD -B $PWD/build \
           -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$PWD/bin \
           -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$PWD/lib \
           -DCMAKE_BUILD_TYPE=RELEASE \
          && cmake --build build -j $(nproc)

  build_wheel_macOS:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-10.15 ]
    steps:
      - uses: actions/checkout@v2

      - name: Git fetch
        run: git fetch --prune --unshallow --recurse-submodules=no

      - name: Install packages
        run: | 
          brew install coreutils \
          && brew install gcc
          brew install boost 
      - name: Build wheel
        run: ./scripts/build-wheels-macOS.sh

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist

  publish_test_pypi:
    name: Publish wheels to Test PyPI
    needs: build_wheel_macOS
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Publish to Test-PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: artifact/
