# This is a basic workflow to help you get started with Actions

name: Code style

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "style"
  style:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # A strategy creates a build matrix for your jobs
    strategy:

      # You can define a matrix of different job configurations
      matrix:

        # Each option you define in the matrix has a key and value
        python-version: [ 3.8 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Setup Python with version from matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install requirements
      - name: Install requirements

        # Runs command-line programs using the operating system's shell
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip list

      # Install pre-commit from .pre-commit-config.yaml
      - name: Install pre-commit
        run: |
          pre-commit install

      # Run pre-commit on all the files in the repo
      - name: Run pre-commit
        run: |
          pre-commit run --all-files --color always --verbose --show-diff-on-failure
