# This is a basic workflow to help you get started with Actions

name: CPP. Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "style"
  build-and-test:

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # A strategy creates a build matrix for your jobs
    strategy:

      # You can define a matrix of different job configurations
      matrix:
        os: [macos-latest, ubuntu-latest] # windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      # Run tests executable
      - name: Run tests
        working-directory: ${{github.workspace}}/build/tests
        run: ctest -C ${{env.BUILD_TYPE}}
